# Generated by Django 5.2.7 on 2025-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
